import {Phone,MessageCircle,MapPin,ArrowRight} from "lucide-react";
const phone="9010495143"; const whatsapp=`https://wa.me/91${phone}`;
const highlights=[["01","Thoughtful Planning","A premium project experience designed around practical living and long-term value."],["02","Future Ready","A clean, modern presentation for a growing real-estate venture."],["03","Customer First","Clear communication and a simple site-visit enquiry journey."]];
export default function Home(){return <main>
<header className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#071827]/90 text-white backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><div className="text-xl font-semibold tracking-[0.18em]">UON</div><div className="text-[10px] uppercase tracking-[0.3em] text-[#c9a35a]">Developers Pvt Ltd</div></div><a href={`tel:${phone}`} className="rounded-full border border-[#c9a35a]/60 px-4 py-2 text-sm">Call Us</a></div></header>
<section className="min-h-[92vh] bg-[#071827] px-5 pb-16 pt-36 text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="mb-5 text-sm uppercase tracking-[0.3em] text-[#c9a35a]">UON Developers</p><h1 className="max-w-3xl text-5xl font-semibold leading-tight sm:text-6xl">Building spaces for a better tomorrow.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">A premium real-estate experience by UON Developers Pvt Ltd. Project details, pricing and approvals will be updated with verified information.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#enquiry" className="inline-flex items-center gap-2 rounded-full bg-[#c9a35a] px-6 py-3 font-semibold text-[#071827]">Enquire Now <ArrowRight size={18}/></a><a href={whatsapp} className="inline-flex items-center gap-2 rounded-full border border-white/25 px-6 py-3 font-semibold"><MessageCircle size={18}/> WhatsApp</a></div></div><div className="rounded-[2rem] border border-white/10 bg-white/5 p-2"><div className="flex min-h-[430px] items-center justify-center rounded-[1.6rem] bg-gradient-to-br from-[#17334a] via-[#102536] to-[#071827] text-center"><div><div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-full border border-[#c9a35a] text-2xl font-bold text-[#c9a35a]">U</div><p className="text-sm uppercase tracking-[0.25em] text-slate-300">Project image coming soon</p><p className="mt-2 text-xs text-slate-400">Replace with your project photo</p></div></div></div></div></section>
<section className="bg-white px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm uppercase tracking-[0.25em] text-[#b58d43]">About UON</p><div className="mt-3 grid gap-8 lg:grid-cols-2"><h2 className="text-4xl font-semibold text-[#071827]">A developer focused on trust, clarity and thoughtful spaces.</h2><div><p className="leading-8 text-slate-600">UON Developers Pvt Ltd is presented here with an original premium real-estate identity. Verified project details can be added as they become available.</p><p className="mt-4 font-semibold text-[#071827]">Director: Uday Simhaa Reddy</p></div></div></div></section>
<section className="bg-[#f7f5f0] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm uppercase tracking-[0.25em] text-[#b58d43]">Why UON</p><div className="mt-8 grid gap-5 md:grid-cols-3">{highlights.map(([n,t,d])=><article key={n} className="rounded-3xl bg-white p-7 shadow-sm"><div className="text-sm text-[#b58d43]">{n}</div><h3 className="mt-5 text-xl font-semibold text-[#071827]">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p></article>)}</div></div></section>
<section id="enquiry" className="bg-[#071827] px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.25em] text-[#c9a35a]">Site Visit</p><h2 className="mt-3 text-4xl font-semibold">Interested in the project?</h2><p className="mt-5 max-w-lg leading-8 text-slate-300">Call or WhatsApp UON Developers to discuss the project and schedule a visit.</p><div className="mt-8 flex flex-wrap gap-3"><a href={`tel:${phone}`} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 font-semibold text-[#071827]"><Phone size={18}/>{phone}</a><a href={whatsapp} className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3"><MessageCircle size={18}/>WhatsApp</a></div></div><div className="rounded-3xl bg-white p-6 text-[#071827]"><div className="grid gap-4"><input className="rounded-xl border p-3" placeholder="Your name"/><input className="rounded-xl border p-3" placeholder="Phone number" type="tel"/><textarea className="min-h-28 rounded-xl border p-3" placeholder="Your requirement"></textarea><a href={`tel:${phone}`} className="rounded-xl bg-[#c9a35a] px-5 py-3 text-center font-semibold">Request a Call</a></div></div></div></section>
<footer className="bg-[#04111c] px-5 py-10 text-slate-300"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold text-white">UON Developers Pvt Ltd</div><div className="mt-1 text-sm">Director: Uday Simhaa Reddy</div></div><div className="flex items-center gap-2 text-sm"><MapPin size={16}/>Project location — to be updated</div></div></footer>
</main>}